### PR TITLE
update gitlab to latest version

### PR DESCRIPTION
**Pull request by ununseptium**
This should refer to the offical docker compose file of gitlab: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/docker/docker-compose.yml

### CODE REVIEW

**Comment by galal-hussein** [comment]
@ununseptium Thanks for the contribution.

I noticed a problem with the new version of Gitlab CE, it requires to set the external URL with the schema and the full FQDN, and since the hostname of the container is set to the same variable it causes an error when you configure the variable to the schema and full FQDN (eg. http://gitlab.example.com/)

```
1/28/2016 5:23:01 PM================================================================================
11/28/2016 5:23:01 PMChef encountered an error attempting to load the node data for "http://gitlab.example.com"
11/28/2016 5:23:01 PM================================================================================
11/28/2016 5:23:01 PM
11/28/2016 5:23:01 PMUnexpected Error:
11/28/2016 5:23:01 PM-----------------
11/28/2016 5:23:01 PMChef::Exceptions::ValidationFailed: Option name's value http://gitlab.example.com does not match regular expression /^[\-[:alnum:]_:.]+$/
11/28/2016 5:23:01 PM
11/28/2016 5:23:01 PMPlatform:
11/28/2016 5:23:01 PM---------
11/28/2016 5:23:01 PMx86_64-linux
11/28/2016 5:23:01 PM
11/28/2016 5:23:01 PM
11/28/2016 5:23:03 PMThank you for using GitLab Docker Image!
11/28/2016 5:23:03 PMCurrent version: gitlab-ce=8.14.0-ce.0
11/28/2016 5:23:03 PM
11/28/2016 5:23:03 PMConfigure GitLab for your system by editing /etc/gitlab/gitlab.rb file
11/28/2016 5:23:03 PMAnd restart this container to reload settings.
11/28/2016 5:23:03 PMTo do it use docker exec:
11/28/2016 5:23:03 PM
11/28/2016 5:23:03 PM  docker exec -it gitlab vim /etc/gitlab/gitlab.rb
11/28/2016 5:23:03 PM  docker restart gitlab
11/28/2016 5:23:03 PM
11/28/2016 5:23:03 PMFor a comprehensive list of configuration options please see the Omnibus GitLab readme
11/28/2016 5:23:03 PMhttps://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md
11/28/2016 5:23:03 PM
11/28/2016 5:23:03 PMIf this container fails to start due to permission problems try to fix it by executing:
11/28/2016 5:23:03 PM
11/28/2016 5:23:03 PM  docker exec -it gitlab update-permissions
11/28/2016 5:23:03 PM  docker restart gitlab
11/28/2016 5:23:03 PM
11/28/2016 5:23:06 PMPreparing services...
11/28/2016 5:23:06 PMStarting services...
11/28/2016 5:23:06 PMConfiguring GitLab package...
11/28/2016 5:23:06 PM/opt/gitlab/embedded/bin/runsvdir-start: line 24: ulimit: pending signals: cannot modify limit: Operation not permitted
11/28/2016 5:23:06 PM/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
11/28/2016 5:23:06 PMConfiguring GitLab...
11/28/2016 5:23:09 PM
11/28/2016 5:23:09 PM================================================================================
11/28/2016 5:23:09 PMChef encountered an error attempting to load the node data for "http://gitlab.example.com"
11/28/2016 5:23:09 PM================================================================================
11/28/2016 5:23:09 PM
11/28/2016 5:23:09 PMUnexpected Error:
11/28/2016 5:23:09 PM-----------------
11/28/2016 5:23:09 PMChef::Exceptions::ValidationFailed: Option name's value http://gitlab.example.com does not match regular expression /^[\-[:alnum:]_:.]+$/
11/28/2016 5:23:09 PM
11/28/2016 5:23:09 PMPlatform:
11/28/2016 5:23:09 PM---------
11/28/2016 5:23:09 PMx86_64-linux
11/28/2016 5:23:09 PM
```

**Comment by ununseptium** [comment]
I added the option to select a uri scheme which is going to be applied to the external_url like this:
```
external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
```
This should resolve the issue.

I also changed all of the version numbers to latest since it should be the same as the version of the docker image.

**Comment by galal-hussein** [comment]
When testing with prefix: https, i am getting the following error:

```
11/28/2016 7:23:08 PM==> /var/log/gitlab/nginx/error.log <==
11/28/2016 7:23:08 PM2016/11/28 17:23:08 [emerg] 1553#0: BIO_new_file("/etc/gitlab/ssl/git.example.com.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/gitlab/ssl/git.example.com.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by ununseptium** [comment]
yeah i see that, of course it's missing. I'm currently reading up on it... but according to the gitlab docs the certs has to be inserted manually.

https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1509
http://docs.gitlab.com/omnibus/settings/nginx.html#enable-https

I don't see another possibility to let the users add their own certificate files right now via the docker-compose approach.

**Comment by galal-hussein** [comment]
@ununseptium You can add the ssl key and cert as variables, and then you can use a sidekick container to copy the key and ssl to /etc/gitlab/ssl and mount this directory to the running server.

**Comment by ununseptium** [comment]
Sadly i'm not fit enough with all this docker / rancher stuff yet. I know how i would ask for the variables but i don't know what i should do then with them. 
Inside the docker-compose i cannot work with stuff like RUN like inside a dockerfile to just create a file with the content of the variable which was my first thought...

So i'm a bit stuck since i don't understand the concept of 'you can use a sidekick container to copy the [...] and mount this directory to the running server', yet.

**Comment by galal-hussein** [comment]
@ununseptium Thanks for the contribution, i will merge and open another PR to fix the HTTPS issue.

**Pull request merged**
