### PR TITLE
Update NeuVector security container release version to rancher1.2.

### PR DESCRIPTION
**Pull request by garyduan**

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @garyduan .. thanks for the PR..

Could you please, update rancher-compose.yml and config.yml accordingly to the new neuvector version??

**Comment by goalotc** [comment]
Hi, @rawmind0,

Thanks for the comment. I updated the PR.

**Comment by garyduan** [comment]
Hi, @rawmind0,

Thanks for the comments, I updated the PR.

**Comment by rawmind0** [comment]
Thanks for the update @garyduan ... 

LGTM...

**Pull request merged**
