### PR TITLE
Update letsencrypt to 0.5.0

### PR DESCRIPTION
**Pull request by annerajb**
Updated letsencrypt to 0.5.0

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @annerajb ... thanks so much for the PR...

As commented in issue https://github.com/rancher/community-catalog/issues/559, due to package is using go templating, docker compose file has to be called as ```docker-compose.yml.tpl```

Otherwise, please squash all the commits in just one.

**Comment by annerajb** [comment]
Tried to do a squash but I believe it did not work out correctly. Or at least visually in GitHub it does not appear to have worked. can you verify?

**Comment by edeckers** [comment]
No, it didn't work. Try:
```
git reset --soft efe9eb1f83e50f39d2e35cce8fd099cc10b2c0c3
git commit -m "Update letsencrypt to 0.5.0"
git remote add upstream git@github.com:rancher/community-catalog.git
git pull --rebase upstream master
git push --force origin master
```

**Comment by annerajb** [comment]
Thanks should be good now.

**Comment by rawmind0** [comment]
Thanks for squash...

@annerajb , volume is not defined correctly. Please, take a look at the change request..

**Comment by rawmind0** [comment]
Thanks @annerajb ...

LGTM..

**Pull request merged**
