### PR TITLE
Update letsencrypt to v0.4.1

### PR DESCRIPTION
**Pull request by janeczku**
- Fixes issue with Rancher-EBS backed volume by adding `driver_opts.size` option to docker-compose
- Adds support for NS1 DNS provider
- Adds support for Azure DNS provider

@galal-hussein Please test with Rancher-EBS storage driver

### CODE REVIEW

**Comment by Treenity** [comment]
I've tried with values of 1e9( for 1gb) but it return error : 
 Activating (Expected state running but got error: Error response from daemon: create letsencrypt_lets-encrypt_11687: VolumeDriver.Create: Failed in create: usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] To see help text, you can run: aws help aws <command> help aws <command> <subcommand> help Unknown options: found, found).

I've read informations about size in the rancher-ebs readme and they like to put --size in GB, so I tried by enter "1", then my volume is now set to 1gb in AWS.

Error message persist, but if I stop and rerun the container, no more error, so something goes bad at creating.

**Comment by janeczku** [comment]
@Treenity thanks for testing. I have changed the instructions in the template to specify the EBS volume size in GiB.

**Comment by Treenity** [comment]
Ok, i will try to test and found why we get à AWS cli error message, i think I can found that in the rancher logs ?

**Comment by Flowman** [comment]
I wanted to test Azure DNS but noticed this is pointing to your v0.4.0 image that does not have that support yet.

When will you update the other image?

**Comment by rawmind0** [comment]
Superseded by https://github.com/rancher/community-catalog/pull/507

**Pull request closed without merging**
