### PR TITLE
Apache

### PR DESCRIPTION
**Pull request by amy**

### CODE REVIEW

**Comment by cloudnautique** [comment]
Need a logo file called catalogImage-apache so that it shows up in the UI. Ideally it would be SVG followed by png.

**Comment by cloudnautique** [comment]
The questions really ballooned, is there a way to simplify. I am not sure its worth all the questions to generate a self signed cert. At that point it is easier to just generate themselves.

Thoughts?

**Comment by paulobezerr** [comment]
IMHO is good to change item name from Apache to "Apache PHP" for example.
You can use Apache to do a lot of different stuff and many times without PHP.

**Comment by cjellick** [comment]
Closing this due to staleness. Feel free to open a new PR if there's still a relevant change to be made. Thanks!

**Pull request closed without merging**
