### PR TITLE
Updated Prometheus and Grafana

### PR DESCRIPTION
**Pull request by Rucknar**
Updates this catalog entry to bring it up to speed with the latest versions of software. 

* Grafana updated to 3.0, some improvements to existing dashboards.
* Prometheus upgraded to 0.18
* Some ports were mapped externally unnecessarily, now sorted 
* Prometheus now monitors its-self, with an associated dashboard. 

Of note, the catalog entry doesn't give you a persistent datastore for Prometheus metrics. Those choosing to upgrade I would expect to lose any historic data.

### CODE REVIEW

**Comment by abhijeetka** [comment]
@Rucknar can you include my changes into your pull request?

**Comment by Rucknar** [comment]
@abhijeetka will take a look, Once this has been merged in, could you rebase and send me a link, I can then take a look and see if we can sort out that issue you had with maintainers at the same time.

**Comment by abhijeetka** [comment]
sure .. closing my pull request for now.

**Comment by Rucknar** [comment]
Thanks @abhijeetka 
@cloudnautique Look okay to merge?

**Comment by cloudnautique** [comment]
@Rucknar On PRs to this stack, I'll look for your LGTM sound good?

**Comment by Rucknar** [comment]
Sounds great, thanks @cloudnautique

**Pull request merged**
