### PR TITLE
Fix typo on consul data volume

### PR DESCRIPTION
**Pull request by chussenot**

### CODE REVIEW

**Comment by chussenot** [comment]
Same as this one... https://github.com/rancher/community-catalog/pull/161/commits/ed670d3739300af8b14e80f2accb80fa8bb91862

**Comment by cloudnautique** [comment]
@galal-hussein, can you take a look at this? I want to say if you give services the label `io.rancher.container.dns: true` you get access to Rancher DNS. That won't make the link work, but you could find service.stack at that point.

**Comment by galal-hussein** [comment]
@cloudnautique It worked perfectly with enabling the DNS, and accessing consul service instead of linking and using net=host

**Comment by cloudnautique** [comment]
@galal-hussein, cool. 
Should this PR be changed to use the labels? Or what is the next step?

**Comment by galal-hussein** [comment]
@cloudnautique I think the PR should use the dns label instead of the link, removing net=host resulted in odd behavior though where consul started to fail.

**Comment by cloudnautique** [comment]
Is this good to go now @galal-hussein

**Comment by galal-hussein** [comment]
@cloudnautique Yes it works fine, tested on Docker 1.11.2 and rancher dev5

**Pull request merged**
