### PR TITLE
Added the Vamp microservices platform catalog entry

### PR DESCRIPTION
**Pull request by stefanvangastel**

### CODE REVIEW

**Comment by stefanvangastel** [comment]
Any chance this request can be merged?

**Comment by galal-hussein** [comment]
@stefanvangastel This looks very good, couple of notes though:

- There is no plan in the catalog for storing volumes, so if one of the containers dies for any reason, then the data will be gone.

- after deploying the catalog, i tried to follow the getting started docs, and deploy the following blueprint:

```
---
name: sava:1.0
gateways:
  9050: sava/webport
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          webport: 8080/http
      scale:
        cpu: 0.2       
        memory: 64MB
        instances: 1
```


but i noticed that the deploy is stuck in state "Deploy initiated" and the vamp container is throwing the following errors:

```
10/27/2016 10:39:08 PM[INFO] [10/27/2016 19:39:08.665] [vamp-akka.actor.default-dispatcher-9] [akka://vamp/user/rancher-driver-actor] Rancher driver - creating service: 6fd83b1fd01f7dd9eb7f97ba2db45d10
10/27/2016 10:39:08 PM19:39:08.689 | ERROR | io.vamp.common.http.RestClient$          |                                          | rsp [POST http://104.197.6.101:8080/v1/projects/1a5/environment/1e12/services] - unexpected status code: 422
```

**Comment by stefanvangastel** [comment]
@galal-hussein Thanks for testing it! Provided the suggested data persistence option. Will look into the deployment issue.

**Comment by galal-hussein** [comment]
@stefanvangastel Unfortunately i am still getting errors even after following your vid, can you provide more details about your setup (Rancher version, Docker version, etc.)

**Comment by stefanvangastel** [comment]
@galal-hussein Succesfully deployed using the following setups:

- macOS 10.12 and Docker 1.12.1 with Rancher server 1.1.4 and same-host Rancher agent/host
- Ubuntu 16.04 and Docker 1.11.2 with Rancher server 1.1.4 and same-host Rancher agent/host
- Ubuntu 16.04 and Docker 1.11.2 with Rancher server 1.1.4 and remote Rancher agent/host (Docker 1.12.1)

Did you try to deploy this blueprint:

```yml
---
name: sava:1.0
gateways:
  9050: sava/port
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          port: 8080/http
      scale:
        cpu: 0.2
        memory: 64MB
        instances: 1
```

Your 422 error implies Rancher is receiving the POST to deploy the Vamp blueprint though cannot process it.

**Comment by rawmind0** [comment]
Hi @stefanvangastel ...

Thanks for the PR and to contribute to rancher. 

I think the strategy for this package is not so good. If you need a consul, a elastics search, kibana,..., they should be deployed with the already existing packges. There is already consul, elasticsearch, kibana,..., catalog packages to do it. 

If you couple consul, elasticsearch or whatever with your package, this software wouldn't get updated by it way or wouldn't be useful to be run alone. Do i explain myself??

It would be better to do a package for the vamp core and a package for the vamp agent gateway. If this package needs some other dependecies, you could set it as external links at deploy time.

I did a first version of them a few months ago...vamp version 0.8.5
https://github.com/rawmind0/vamp-rancher-catalog

Best regards....

**Comment by galal-hussein** [comment]
@stefanvangastel I agree with @rawmind0, if i may add to your input, for example the logstash catalog depends on an existing[ elasticsearch service ](https://github.com/rancher/community-catalog/blob/master/templates/logstash/1/rancher-compose.yml#L43-L50), you can follow the same idea from the previous link and use it in the catalog.

**Comment by stefanvangastel** [comment]
Oke, I understand. Will look at both the current example and the logstash
dependency example!

Op di 1 nov. 2016 18:39 schreef Hussein Galal <notifications@github.com>:

**Comment by rawmind0** [comment]
@stefanvangastel you could see for example, how to link vamp with a zookeeper key server (in your case consul) in the repo that i've pasted before.... ;)

https://github.com/rawmind0/vamp-rancher-catalog/blob/master/templates/vamp/0/rancher-compose.yml

**Comment by stefanvangastel** [comment]
@rawmind0 Thanks, I will. Why didnt your efforts make it to the public catalog btw?

**Comment by olafmol** [comment]
Sounds like it might be valuable to see how we can merge the @rawmind0 and @stefanvangastel catalogue packages to get the best of both worlds ;)

Keep in mind though: the reason for us to package ES+Logstash+Haproxy with Vamp is that we use our custom configuration files for these applications, and not all platforms provide exposing these configuration settings during deployment from a  catalogue. Don't know about Rancher but @rawmind0 you will probably know if that would work :)

Looking forward to see this working so we can start supporting and improving it. Will add our DevOps engineer Mikael to this discussion too.

**Comment by rawmind0** [comment]
Hi @olafmol ....

Separate packages was working without any problem with vamp 0.8.5 
In that version, ES catalog package didn't need any special config, logstash was configured with the catalog packages. There wasn't a separate haproxy piece, vamp gateway agent instead (separate package).
 I mean, with vamp 0.8.5 you could do a full deployment in rancher with catalog packages, zookeeper, ES, kibana, logstash, vamp and vamp agent gateway.

Is some different in 0.9.0 version?? 

I propose to make and initial PR with the 0.8.5 version, that was working in the previous test, and upgrade it to the current vamp version, but trying to maintain separated pieces.  

What do you think??

**Comment by rawmind0** [comment]
I forget.....

Previous test was done with zookeeper instead consul as vamp key type, but consul has catalog package too... 

Vamp catalog package is already able to configure vamp key and db parameters and services links.

You could try the packages before the PR, adding this catalog to you rancher server,
https://github.com/rawmind0/vamp-rancher-catalog

**Comment by olafmol** [comment]
@rawmind0 tnx Raul, we're going to check it out, should also work with Vamp 09x

**Comment by stefanvangastel** [comment]
Closing this mergerequest in favor of re-designing and rebuilding the solution following @rawmind0 and @galal-hussein suggestions.

New MR will link to this one for reference.

**Pull request closed without merging**
