### PR TITLE
[TASK] change taiga templates

### PR DESCRIPTION
**Pull request by KartoffelToby**
Change the Docker Images, working Conf

### CODE REVIEW

**Comment by lilnate22** [comment]
+1 current taiga doesnt work at all

**Comment by cloudnautique** [comment]
@KartoffelToby,

 Thanks for taking a pass at this. I see there are some python and json files in the folder. Those will not be picked up by Rancher, and need to be embedded in a container. 

 Also, while we are updating the template, we should add a data volume side kick to the Postgres container. That way we can upgrade it and make scheduling decisions about it later.

**Comment by KartoffelToby** [comment]
@cloudnautique OK. I'll copy the files to the Image and add the Volume.

**Comment by cloudnautique** [comment]
Ping @KartoffelToby

**Comment by KartoffelToby** [comment]
Sorry i was really busy.

Config files are now in the Container.
The postgres Container has a Volume that can be set via rancher-compose file

**Comment by lilnate22** [comment]
+1 @KartoffelToby 👍

**Comment by MichelDiz** [comment]
This is not working. I cannot access either locally, or even in the network. (using a custom host locally) There's nothing in "TAIGA_HOSTNAME taiga.test.de"

**Pull request merged**
