### PR TITLE
FIX for issue #28

### PR DESCRIPTION
**Pull request by matisku**
This will fix an issue #28.
I created a new version of configuration, with auto-creation of mysql database.

### CODE REVIEW

**Comment by matisku** [comment]
I the the same CI error for pull request 247. Can you please explain what I'm missing?

**Comment by dpattmann** [comment]
Just take a look into this PR https://github.com/rancher/community-catalog/pull/249

**Comment by dpattmann** [comment]
Why have you closed your PR?

**Comment by matisku** [comment]
I'm closing this PR for now as I want to clean up my for and create separate feature branch for this fix. Also I will make Gogs better for image upgrades with additional data sidekicks.

**Comment by matisku** [comment]
I'm closing this PR for now as I want to clean up my for and create separate feature branch for this fix. Also I will make Gogs better for image upgrades with additional data sidekicks.

**Pull request closed without merging**
