### PR TITLE
smart(?)er wait for listening catalog service

### PR DESCRIPTION
**Pull request by nrvale0**
We were getting test flakes in CI because the static wait for start of Rancher Catalog service was expiring without service start. Make the wait check for listening tcp/8088 as a reasonable predicate for working Catalog service.

@LLParse @cloudnautique

### CODE REVIEW

**Comment by LLParse** [comment]
By using `netstat`, we introduce a dependency...which should be OK as long as tests are always performed from within a Linux container with the 'net-tools' package installed. For reference, the [/dev/tcp](http://www.tldp.org/LDP/abs/html/devref1.html#DEVTCP) device file can be used in bash scripts to do the same thing in a platform-agnostic way.

LGTM

**Comment by nrvale0** [comment]
@LLParse @cloudnautique Had some problems getting the fdes sorted out with /dev/tcp so falling back to a curl. I can't imagine we'd ever have a build container which doesn't have curl|wget.

**Comment by LLParse** [comment]
If you're going to use curl, could you provide the `-s` flag so we don't get ugly output in the logs:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    
```

**Comment by nrvale0** [comment]
@LLParse With the exception of a little stderr output on failed poll as progress/feedback, that's less noisy.

**Comment by cloudnautique** [comment]
@nrvale0 can you rebase?

**Comment by nrvale0** [comment]
@cloudnautique Done

**Comment by rawmind0** [comment]
Hi @nrvale0 ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Pull request closed without merging**
