### PR TITLE
Allowing TTL to be specified by Env var

### PR DESCRIPTION
**Pull request by benyanke**
This should really be a configurable option

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @benyanke , thanks for the PR and contribute.

Couple of questions, why are your updating files at `infra-templates/digitalocean-dns/0` and `infra-templates/digitalocean-dns/3` versions?? Why don't you update all versions or just the last one??

**Comment by benyanke** [comment]
I previously misunderstood the versioning - I see the issue with that now. Is there an easy way to delete a commit from a PR or should I start over?

**Comment by rawmind0** [comment]
You could do it with `git reset` in your forked repo. If not you could start over.

**Comment by benyanke** [comment]
ok, force pushed my cleaned up branch - give it a look. Thanks @rawmind0

**Comment by rawmind0** [comment]
Thanks @benyanke ..

LGTM...

**Pull request merged**
