### PR TITLE
New templates: Registry, Logspout (community)

### PR DESCRIPTION
**Pull request by sshipway**
Logspout community template:
- Copy of existing Rancher-provided template, with additions
- Added additional configuration parameter SYSLOG_HOSTNAME to specify Environment
- Allows logs to be tagged with Environment name rather than underlying Docker hostname

Registry template:
- Built using registry:2 and Portus frontend to make secure registry with web frontend
- Optional LDAP authentication or local authentication
- SSL enabled using either provided certificate or auto-generated self-signed cert
- Custom build of Portus container with additional startup options (Portus does not have an official container build as yet)
- Template does not use persistent storage, but this would usually be required
- Detailed documentation

### CODE REVIEW

**Comment by Rucknar** [comment]
Awesome :)

**Comment by xinity** [comment]
Awesome, exactly what i've been searching for !

**Comment by cloudnautique** [comment]
Awesome! I was hoping you would submit this entry.

Can you squash the commits please.

**Comment by sshipway** [comment]
... not sure how to 'squash commits' (I assume you mean combine them into a single one).  I will investigate the git docco as I cant find an option searching on the website.  Probably I'm just too new to git....

**Comment by cloudnautique** [comment]
I typically do: (You should cp the directory before hand incase it blows up :) )

git checkout my_branch
git fetch upstream (I usually have origin as my fork, upstream as the upstream)
git rebase -i upstream/master

This will show you a list of commits... the ones you want to squash replase the first field with `s`

**Comment by sshipway** [comment]
@cloudnautique - thanks for the pointers.  I had a few conflicts and accidentally duplicated all my commits somehow, but now it seems to be OK.

**Pull request merged**
