### PR TITLE
fix Aliyun DNS issue

### PR DESCRIPTION
**Pull request by loganhz**
Alibaba Cloud DNS API changed again. They have reverted the change for their API. 
So I have to update the catalog for fix.

### CODE REVIEW

**Comment by yasker** [comment]
Please hold on merging this. We need to get a new release of External DNS.

**Comment by loganhz** [comment]
@yasker it is ready for review.

**Comment by deniseschannon** [comment]
@loganhz Can you split this into 2 commits? One for the copy from the previous folder and one with the changes that were made?

**Comment by yasker** [comment]
Linked to: https://github.com/rancher/rancher/issues/9382

**Comment by loganhz** [comment]
@deniseschannon done. 
thanks

**Pull request merged**
