### PR TITLE
Bump version for px-dev to 1.0.6

### PR DESCRIPTION
**Pull request by jsilberm**
Add -c and -k options for px-dev to facilitate automation.
Bumped version to 1.0.6

### CODE REVIEW

**Comment by jsilberm** [comment]
Okay this should be fixed.

**Comment by jsilberm** [comment]
Okay should be good to go?

**Comment by jsilberm** [comment]
Hello?   I'm happy to take any action needed to move this forward.   If there's a sticking point somewhere, please let me know.   Thanks!  -Jeff

**Comment by rawmind0** [comment]
Hi @jsilberm ...sorry about the delay...

Thanks so much for the PR... LGTM...:)

Raul

**Pull request merged**
