### PR TITLE
Added OpenNebula Machine-Driver

### PR DESCRIPTION
**Pull request by km4rcus**
Added the [OpenNebula](https://github.com/OpenNebula/docker-machine-opennebula) machine-driver

### CODE REVIEW

**Comment by galal-hussein** [comment]
@km4rcus Thanks for the machine template, I noticed the UI is a bit confusing to the users, like authentication options (user, password, xmlrpc) are mixed with other options, maybe its useful if you separate the authentication process from other options.

**Comment by km4rcus** [comment]
@galal-hussein I have created a custom UI for the OpenNebula driver (https://github.com/km4rcus/ui-driver-opennebula). How can I add it to the machine driver template?

**Comment by vincent99** [comment]
There are 3 files we look for:  `url`, `checksum`, and `uiUrl` (or alternately `ui-url` after 1.2.0-pre3).

**Comment by km4rcus** [comment]
@galal-hussein @vincent99 I have added the uiUrl for the OpenNebula custom UI. Is it ok?

**Comment by galal-hussein** [comment]
@km4rcus Thanks, I can see now the custom UI for OpenNebula when creating a machine, however @vincent99 when creating a new instance i can see the instance created on OpenNebula but i can't see any progress in the UI, I am getting `No hosts or containers yet.`

The server logs:

```
time="2016-11-16T15:19:26Z" level=info msg="Creating Machine" eventId=1607e255-0c22-47e5-9afd-aad97d01947e resourceId=1ph8 
time="2016-11-16T15:19:26Z" level=info msg="Cmd slice: [create -d opennebula --engine-install-url https://releases.rancher.com/install-docker/1.12.sh --opennebula-cpu 1 --opennebula-memory 512 --opennebula-network-name cloud --opennebula-password xxxxxxx --opennebula-ssh-user docker --opennebula-template-id 1 --opennebula-user xxxxxxx --opennebula-vcpu 1 --opennebula-xmlrpcurl http://52.87.226.122:2633/RPC2 test1]" 
time="2016-11-16T15:19:26Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/45990772-795f-4cac-9305-1e0352e4580b/certs/ca.pem" resourceId: =1ph8 
time="2016-11-16T15:19:27Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/45990772-795f-4cac-9305-1e0352e4580b/certs/cert.pem" resourceId: =1ph8 
time="2016-11-16T15:19:28Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph8 
time="2016-11-16T15:19:28Z" level=info msg="stdout: Creating machine..." resourceId: =1ph8 
time="2016-11-16T15:19:28Z" level=info msg="stdout: (test1) Creating SSH key..." resourceId: =1ph8 
time="2016-11-16T15:19:28Z" level=info msg="stdout: (test1) Starting\t VM..." resourceId: =1ph8 
time="2016-11-16T15:20:13Z" level=info msg="stdout: (test1) Waiting for SSH..." resourceId: =1ph8 
```

**Comment by km4rcus** [comment]
@galal-hussein @vincent99 Any news on this?

**Comment by vincent99** [comment]
@km4rcus Ijn Rancher 1.2.x drivers should create a `host` resource directly instead of creating a `machine` (which eventually indirectly creates a host).  Compare and update your code against the current `ui-driver-skel`, which works with both 1.1.x and 1.2.x.

**Comment by km4rcus** [comment]
Thanks @vincent99. I have updated the component.js and I have tested it with the v1.2.0-rc1 release. Now it works.

**Comment by rawmind0** [comment]
Hi @km4rcus ...

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by km4rcus** [comment]
@rawmind0 No problem. I rebased it.

@galal-hussein @vincent99 I tested again with the latest release v1.2.0 and it works. I noticed that in the UI machine drivers page the OpenNebula logo doesn't appear anymore as in the v1.2.0-rc1 but it appears only in the add hosts page.

**Comment by galal-hussein** [comment]
@km4rcus I can see the logo picture in both places in v1.2.0, i tested the machine driver and it worked.

LGTM.

**Comment by galal-hussein** [comment]
@rawmind0 can you give the template a second review.

**Comment by rawmind0** [comment]
@km4rcus... Thanks so much for the PR, nice... :)

@galal-hussein..Tested and working...LGTM

**Pull request merged**
