### PR TITLE
Minor Portworx specific updates

### PR DESCRIPTION
**Pull request by jsilberm**
Just a few minor updates to the Portworx catalog.

Thanks.

### CODE REVIEW

**Comment by jsilberm** [comment]
We fixed the link so it wouldn't throw warnings, as you asked. 
Everything should be good now.
Can you please approve or let us know what needs to be fixed?

Thanks.

**Comment by cloudnautique** [comment]
Sure. The changes can't be merged due to conflicts. Can you get this to a state where we can merge? Looks like the README.md has issues.

**Comment by jsilberm** [comment]
The existing README uses https for our docs url, and we are trying change that to just http.   That's one of the main reasons for this PR.

Any other way we should be addressing this?

**Comment by jsilberm** [comment]
[Here](https://github.com/rancher/community-catalog/pull/289/commits/457ee1db53aaf2750128691d09783bfecff23d1b) is the "conflict" for you to see.

**Comment by cloudnautique** [comment]
I'd suggest a feature branch with just this change that starts from the current rancher/community-catalog master. The issue I think is that its trying to remerge all of the commits that were merged previously.

**Comment by jsilberm** [comment]
Got it.  Will do.   Thanks

**Pull request closed without merging**
