### PR TITLE
Migrate to Prometheus 2.1.0 and Grafana 5.0.0

### PR DESCRIPTION
**Pull request by sliard**
Change Prometheus and Grafana version.
Will work only when infinityworks upgrade infinityworks/prom-conf with this pull request : 
https://github.com/infinityworks/prom-conf/pull/6

### CODE REVIEW

**Comment by Rucknar** [comment]
@sliard Looks good, it's probably worth updating the default version to match your new entry. Can be done in the main config file, you okay to push that up as an update?

**Comment by sliard** [comment]
No problem. I just didn't want to force this update and let you choose. :)
For the moment I set it has version 3.0.1 but don't you think 4.0.0 is better ?
Let me know what you prefer and I will update.

**Comment by Rucknar** [comment]
Won't force it on anyone. That version number needs adjusting in the base folder config.yaml file to update the default version. If we want to hold off on that for a little while though, that's fine.

**Comment by Rucknar** [comment]
@cloudnautique Looks good to merge to me, haven't had chance to test myself.

**Comment by rawmind0** [comment]
Hi guys, @sliard thanks for the PR, @Rucknar thanks for the review.

Tested and working fine. 

LGTM

**Pull request merged**
