### PR TITLE
Add setting for Sematext Cloud region EU/US

### PR DESCRIPTION
**Pull request by megastef**

### CODE REVIEW

**Comment by megastef** [comment]
I don't think build fails because of my changes.

**Comment by megastef** [comment]
Could anyone pls. advise why checks fail?

**Comment by superseb** [comment]
You are changing a version in-place, please create a new version folder and create a new version of the item so people can use the old and upgrade to the new.

The checks fail because you changed the version in the main `config.yml` but there is no corresponding version in the `rancher-compose.yml` of the only version of this catalog item (`0`)

**Comment by megastef** [comment]
@superseb thank you. The version number got adjusted in rancher-compose.yml and checks passed.

**Comment by rawmind0** [comment]
Hi @megastef ... Build is working fine now, but as @superseb requested before, could you please generate a new version folder to add your files??  

Basically move `templates/sematext/0/docker-compose.yml` to `templates/sematext/1/docker-compose.yml` and `templates/sematext/0/rancher-compose.yml` to `templates/sematext/1/rancher-compose.yml`

**Pull request closed without merging**
