### PR TITLE
OpenVPN Server with multiple authentication backends

### PR DESCRIPTION
**Pull request by AlexisDucastel**
Hi there,

Here are three new catalog entries with OpenVPN Server using differents kind of authentication backends :
- ldap
- HTTP Basic
- HTTP Digest

OpenVPN server is based on docker image https://hub.docker.com/r/mdns/rancher-openvpn/ , I splitted it in three diferent entries to simplify stack deployement.

Any comment would be welcome !

### CODE REVIEW

**Comment by djskinner** [comment]
I've been using this with success https://github.com/nixelsolutions/rancher-vpn-server. Is there anything to be learnt from this implementation?

I never managed to get it working but it would be amazing if the Rancher OpenVPN Server could add DNS entries to client in order to resolve containers in the rancher managed network by their FQDN.

**Comment by AlexisDucastel** [comment]
Hi,

The main difference between this implementation and nixelsolutions's one, is that nixelslutions is an OpenVPN based on certificates (server and client), that require to open a ssh server listenener to be able to generate client certificates and configuration.

My version is based on "first run generated" server certificates, but with credentials auhtentication with multiple authentication backends (ldap, http basic or http digest for now).

The ovpn config file is the same for each client (only one config file to spread to users), and use OpenVPN native interactive authentication mode to retrieve client credentials. These are challenged against the choosen authentication backend, for example ldap, and if credentials are good, the OpenVPN accept the connection and give access to rancher managed network.

It allows IT team to give VPN access with central credential management.

**Comment by AlexisDucastel** [comment]
For DNS entries, i'm currently searching for a simple and efficient solution.

**Comment by vincent99** [comment]
With the next release (0.61+) I think you could just iptables forward TCP/UDP 53 to 169.254.169.250 in the VPN container and point the clients resolv.conf to it; there are now full `$service.$stack.rancher.internal` entries for the whole environment in the default answers config for the rancher-dns server

**Comment by AlexisDucastel** [comment]
Hi @vincent99 

I actually push dns configuration and route to 169.254.169.250 in my openvpn client config, i can reach rancher internal dns without any problem, but it cannot resolve any $service.$stack.rancher.internal, nor from my computer on vpn, nor in a service of a stack ...

```
C:\Users\Alexis>dig logstash-collector.Logs.rancher.internal.

; <<>> DiG 9.10.2-P3 <<>> logstash-collector.Logs.rancher.internal.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25391
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;logstash-collector.Logs.rancher.internal. IN A

;; AUTHORITY SECTION:
.                       10635   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2016030900 1800 900 604800 86400

;; Query time: 48 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Wed Mar 09 17:21:16     2016
;; MSG SIZE  rcvd: 144
```
Will the feature be available with 0.61+ only ?

**Comment by vincent99** [comment]
Yes, that would be the "With the next release (0.61+)" part :smile:

**Comment by AlexisDucastel** [comment]
Okay that's great ! i thought it was for the iptable hint that you mentionned next release.
You guys really rocks ;)

**Pull request merged**
