### PR TITLE
sysdig-cloud: Cut logs at 100mb and make a system service

### PR DESCRIPTION
**Pull request by jmreicha**
Adds `log-opt` to cut logs every 100mb so disk sizes don't grow and makes it a system service.

### CODE REVIEW

**Comment by jmreicha** [comment]
Do I need to worry about the failing checks?

**Comment by cloudnautique** [comment]
Would you mind rebasing with master just to make sure. We had some issues when we cut over CI systems.

**Comment by jmreicha** [comment]
@cloudnautique Done.

**Comment by cloudnautique** [comment]
@jmreicha, looks like this was a merge commit. 

We need it rebased, I don't think I can merge this with out it getting wonky.

**Pull request closed without merging**
