### PR TITLE
Fix storage container for Jenkins

### PR DESCRIPTION
**Pull request by NavidZisky**
Jenkins was not starting at all due to permissions error. This fix solves issue. Tested.

### CODE REVIEW

**Comment by cloudnautique** [comment]
Under which context? I'm a bit hesitant to merge this, as we have seen it running.

**Comment by NavidZisky** [comment]
Hi. I haven't seen jenkins working in rancher. Every time (I tested 3 versions of rancher on 5 different environments). Every time after attempt to run jenkins it was taking so much time that after few times I looked into logs (docker logs [jenkins_container]) and I saw it's in loop 1. downloading plugins... 2. can't write to /var/jenkins_home.

**Comment by NavidZisky** [comment]
So, I just spin up again new installation and this is log from jenkins-ci_jenkins-primary_1 container:

29/03/2016 07:39:31Downloading credentials:latest
29/03/2016 07:39:35Downloading greenballs:latest
29/03/2016 07:39:37Downloading git:latest
29/03/2016 07:39:39Downloading junit:latest
29/03/2016 07:39:40Downloading git-client:latest
29/03/2016 07:39:42Downloading github-api:latest
29/03/2016 07:39:44Downloading github-oauth:latest
29/03/2016 07:39:46Downloading github:latest
29/03/2016 07:39:48Downloading plain-credentials:latest
29/03/2016 07:39:49Downloading scm-api:latest
29/03/2016 07:39:50Downloading ssh-credentials:latest
29/03/2016 07:39:52Downloading ssh-slaves:latest
29/03/2016 07:39:53Downloading swarm:latest
29/03/2016 07:39:54touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied
29/03/2016 07:39:54Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?


You have seen it running maybe for few seconds - because it's starting (showing active) and stopping after few seconds - as You see in logs for few seconds it downloading plugins - then throwing error

**Comment by NavidZisky** [comment]
And this is log from jenkins-ci_jenkins-primary_1 after applying my changes:

29/03/2016 07:46:02Downloading credentials:latest
29/03/2016 07:46:03Downloading greenballs:latest
29/03/2016 07:46:07Downloading git:latest
29/03/2016 07:46:08Downloading junit:latest
29/03/2016 07:46:10Downloading git-client:latest
29/03/2016 07:46:12Downloading github-api:latest
29/03/2016 07:46:13Downloading github-oauth:latest
29/03/2016 07:46:15Downloading github:latest
29/03/2016 07:46:16Downloading plain-credentials:latest
29/03/2016 07:46:17Downloading scm-api:latest
29/03/2016 07:46:18Downloading ssh-credentials:latest
29/03/2016 07:46:20Downloading ssh-slaves:latest
29/03/2016 07:46:21Downloading swarm:latest
29/03/2016 07:46:23Running from: /usr/share/jenkins/jenkins.war
(...)
29/03/2016 07:46:25Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")

**Comment by cloudnautique** [comment]
Yep, you are correct! Thank you.

**Comment by cloudnautique** [comment]
Can you squash the commits down to one?

**Comment by NavidZisky** [comment]
Sure. Sorry for this double commit. Done.

**Pull request merged**
