### PR TITLE
Adding machine template for ProfitBricks

### PR DESCRIPTION
**Pull request by matfin**
This PR adds an entry to machine-template for the ProfitBricks [ui](https://github.com/profitbricks/ui-driver-profitbricks) and [machine](https://github.com/profitbricks/docker-machine-driver-profitbricks) drivers.

The compiled ```component.js``` file is now referenced from the latest [release](https://github.com/profitbricks/ui-driver-profitbricks/releases/tag/v1.0.0) of the ui driver.

### CODE REVIEW

**Comment by matfin** [comment]
Hi Vincent,

I will host the component.js files and resubmit. 

Thanks,

Matt

**Comment by alibazlamit** [comment]
@vincent99 We have uploaded the custom component files to a Profit Bricks github page [here](https://profitbricks.github.io/ui-driver-profitbricks/docs/1.1.0/component.js), i have tested it from the rancher ui and it serves properly.

**Comment by alibazlamit** [comment]
@vincent99 a friendly nudge, could you updated the status of this PR.
Thanks.

**Comment by vincent99** [comment]
LGTM.. note that in current versions of Rancher 1.12 is the default anyway so `Note: Ubuntu 16.04 requires Docker v1.12 or greater. You will need to change the Docker Install URL under the Advanced Options tab.
Volume size (GB)` may not be needed

**Pull request merged**
