### PR TITLE
Updated minio to release/2017-11-22_1

### PR DESCRIPTION
**Pull request by mschneider82**
Just updated & tested minio release/2017-11-22_1

#660

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @mschneider82 , thanks so much for the PR and contribute.

Could you please add your files to a new version folder `templates/minio/2`??

**Comment by mschneider82** [comment]
@rawmind0  done

**Comment by rawmind0** [comment]
Thanks @mschneider82 ...

LGTM...

**Comment by rawmind0** [comment]
Thanks @mschneider82 ...

LGTM...

**Pull request merged**
