### PR TITLE
Bump Weave Scope to version 1.1.0

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by errordeveloper** [comment]
cc @faddat

**Comment by galal-hussein** [comment]
@errordeveloper Thanks for your contribution!

Can the new version be added as a separate folder `1/`, so that the user can have the ability to select version to deploy.

**Comment by errordeveloper** [comment]
> Can the new version be added as a separate folder `1/`...

I was wondering whether I had to do this or not, but previously `weavescope` was updated in `0/`...

> ...so that the user can have the ability to select version to deploy.

From our perspective, there is no good reason to not use latest version available.

**Comment by galal-hussein** [comment]
@errordeveloper This will depend on the application, so my question is weavescope newer version will have major distinct features than the previous version that will make sense to separate the two versions?

**Comment by errordeveloper** [comment]
> ...so my question is weavescope newer version will have major distinct features than the previous version that will make sense to separate the two versions?

I don't think so. Please see [release notes](https://github.com/weaveworks/scope/blob/v1.1.0/CHANGELOG.md) for details.

**Comment by galal-hussein** [comment]
@errordeveloper Thanks for the clarification.

LGTM

**Comment by errordeveloper** [comment]
Thanks!!

**Pull request merged**
