### PR TITLE
Adding Heapster Kubernetes Template

### PR DESCRIPTION
**Pull request by galal-hussein**
This PR will add Heapster Grafana and Influxdb stack to monitor Kubernetes environment.

### CODE REVIEW

**Comment by galal-hussein** [comment]
@wlan0 ^

**Comment by wlan0** [comment]
@alena1108 ^^

**Comment by alena1108** [comment]
LGTM

**Comment by alena1108** [comment]
@vincent99 can you give it a second review?

**Comment by wlan0** [comment]
@galal-hussein This needs to be placed to `kube-system` namespace by default, since this is a system service.

**Comment by galal-hussein** [comment]
@wlan0 All services and rcs already have `namespace: kube-system`

**Comment by wlan0** [comment]
thanks @galal-hussein . LGTM

**Comment by wlan0** [comment]
@galal-hussein We are going to start using kubectl 1.4, which doesnt play well with `---`, can you ensure that there are no trailing whitespaces after `---` in your template?

**Comment by galal-hussein** [comment]
@wlan0 Done!

**Pull request merged**
