### PR TITLE
Added named data container to jenkins-swarm

### PR DESCRIPTION
**Pull request by dpattmann**
See https://github.com/rancher/community-catalog/pull/218 for more informations

### CODE REVIEW

**Comment by cloudnautique** [comment]
can you rebase? Its got some strangeness with the secrets bridge commit showing up.

**Comment by dpattmann** [comment]
Hey @cloudnautique, I updated my branch.

**Comment by rawmind0** [comment]
Hi @dpattmann ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by dpattmann** [comment]
Hi @rawmind0, I update my PR.

**Pull request closed without merging**
