### PR TITLE
Added RabbitMQ with clustering

### PR DESCRIPTION
**Pull request by ddmng**
I added a RabbitMQ stack that supports clustering via Rancher's Scale feature.
It's inspired by elasticsearch-2 structure, so the cluster is made declaratively on new nodes' config file.
I've tested a bit adding and removing nodes and it seems to be stable. I'll work on this for some day to add some config parameter and to not start two rabbit instances on same node.
I use `rabbit:3.6.1-management` image so if you want to see the management interface just add a balancer mapping 15672 service's port on one you prefer.

See https://github.com/rancher/catalog-dockerfiles/pull/61 for corresponding `-conf` image

### CODE REVIEW

**Comment by ddmng** [comment]
Hi @cloudnautique 
Interested to this rabbitmq image?

**Comment by iamthemuffinman** [comment]
+1

**Comment by ppiccolo** [comment]
+1

**Comment by andyshinn** [comment]
Awesome work. I will try and test it out in the coming days.

**Comment by andyshinn** [comment]
The the `rancher/rabbitmq-conf:v0.1.0` image pushed somewhere that I can pull and test this out with?

**Comment by ddmng** [comment]
You should build it from my catalog-dockerfile fork.  See the corresponding PR at rancher/catalog-dockerfiles#61

**Comment by ddmng** [comment]
I just pushed `rancher/rabbitmq-conf:v0.1.0`  to https://hub.docker.com/r/rdaneel/rabbitmq-conf/

**Comment by andyshinn** [comment]
Are you able to get a load balancer to work in front of it? I just get `503 Service Unavailable` even though all the container IPs appear correctly in the `haproxy.conf`.

**Comment by andyshinn** [comment]
Ah, my bad. Issue with this specific host talking on the Rancher network. Seems to work fine on another host. So far so good!

**Comment by andyshinn** [comment]
I've been using this in staging without issue for a while. I plan to set up a production cluster using it soon. What is the possibility of getting this merged in?

**Comment by ddmng** [comment]
Thanks @cloudnautique @andyshinn . Anyway this requires merging PR with the  `- conf` image in catalog-dockerfile: https://github.com/rancher/catalog-dockerfiles/pull/61

**Comment by ddmng** [comment]
.... and you should add `rancher/rabbitmq-conf` to your docker hub in order to avoid the current `Error: image rancher/rabbitmq-conf not found` error in deploying.

**Comment by cloudnautique** [comment]
@ddmng, I missed that... 

Can you build and publish the image? Catalog-dockerfiles is just for stuff that Rancher Labs does. In the community catalog we do not need to host or own the files. I know we need to do a better job documenting this stuff.

**Comment by cloudnautique** [comment]
By build / publish, I mean build the image and publish to your own docker hub namespace, then update the catalog?

**Comment by andyshinn** [comment]
I think that part is actually already done. I've been using image rdaneel/rabbitmq-conf:0.1.0 in testing. I also, didn't realize those Dockerfiles were Rancher specific...

**Comment by ddmng** [comment]
Opened PR #207

**Comment by andyshinn** [comment]
@ddmng is the rabbitmq-conf image source published somewhere? I want to make some additions for modifying `net_ticktime` and `cluster_partition_handling`. The current setup isn't very reliable in Rancher. But I think it can be tuned to handle network partitions better and to possibly autoheal itself.

**Comment by ddmng** [comment]
@andyshinn This is the link to the source:
https://github.com/ddmng/catalog-dockerfiles/tree/master/rabbitmq/0.1.0
Even if i merge the PR I will not be able to build the new image version back on docker hub before Friday.

**Pull request merged**
