### PR TITLE
Updated to make Prometheus config more dynamic

### PR DESCRIPTION
**Pull request by Rucknar**

### CODE REVIEW

**Comment by cloudnautique** [comment]
Did you need to add more questions or anything? Just checking before I merge.

**Comment by Rucknar** [comment]
Nope, this is just to address some feedback i've had around adding new hosts.

**Comment by Rucknar** [comment]
@cloudnautique If you leave it for a few hours. Just found a bug, i'll fix and squash it into this request.

**Comment by cloudnautique** [comment]
OK. I'll merge on the next go round. Thanks.

**Comment by Rucknar** [comment]
@cloudnautique Ready to go.

**Comment by Rucknar** [comment]
Thanks @cloudnautique !

**Pull request merged**
