### PR TITLE
chore: upgrading to latest stable version 2.3.6

### PR DESCRIPTION
**Pull request by 4F2E4A2E**
https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.6

### CODE REVIEW

**Comment by cjellick** [comment]
Closing this due to staleness. Feel free to reopen or open a new PR if there's still a relevant change to be made. Thanks!

**Comment by 4F2E4A2E** [comment]
Why is it not being merged or reviewed? The PR is ready to be merged like a year ago.

**Comment by cjellick** [comment]
Well, this is primarily because the project that that this is for (Rancher 1.6) is now end of life. We aren't really accepted enhancements. Sorry we didn't get to this sooner.

**Comment by 4F2E4A2E** [comment]
Thank you for the info.

**Pull request closed without merging**
