### PR TITLE
Update Jenkins catalog entry to latest (2.7.1)

### PR DESCRIPTION
**Pull request by ovidiub13**
I've just bumped the version number. I'd like to also check if the https://hub.docker.com/r/rancher/jenkins-plugins/ image is still compatible with this version, but the sources are nowhere to be found.

### CODE REVIEW

**Comment by ovidiub13** [comment]
Forum discussion: https://forums.rancher.com/t/sources-for-rancher-jenkins-plugins/3474

**Comment by cloudnautique** [comment]
I'm not too familiar with the 2.x Jenkins server. Is the upgrade path from the 1.x versions straight forward? Will it work without change?

**Comment by ovidiub13** [comment]
Acording to [this](https://wiki.jenkins-ci.org/display/JENKINS/Upgrade+wizard) it is. Should I perform a test?

**Comment by cloudnautique** [comment]
@ovidiub13 I would be curious what you find. Though it does seem like it would be straight forward.

**Comment by rawmind0** [comment]
Hi @ovidiub13 ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by ovidiub13** [comment]
Personally, I'm not using this image anymore, since it took waaaaaaaaay to long to get it updated. I've built my own docker-compose file.

Right now, I have no interest for myself to redo this, but I'll look into it right now for the community.

**Comment by ovidiub13** [comment]
I could not update this branch, so I made a new branch and a new Pull Request #349. I'm closing this.

**Pull request closed without merging**
