### PR TITLE
Adding Rancher Server with Nginx proxy and Let's Encrypt SSL in catalog

### PR DESCRIPTION
**Pull request by KrustyHack**
Ay,

I hope my work is fine.

Regards,

### CODE REVIEW

**Comment by djskinner** [comment]
Out of curiosity how does running a rancher server instance as a stack from a rancher catalog entry actually work? What about the existing instance of rancher server?

**Comment by KrustyHack** [comment]
Ay,

I don't understand your question (french here :p). There is no problem if you deploy a rancher server from catalog to another server.

**Comment by djskinner** [comment]
You understood fine since you answered my question perfectly. Thanks. :)

**Comment by djskinner** [comment]
My only other suggestion would be not to use `latest` tags. It happened to me once before where the Prometheus catalog entry broke when a new version of one of the images was released. If the versions are locked down then this cannot happen.

**Comment by sshipway** [comment]
I agree with the "no :latest tags" rule for templates.  You can always release a new template version if you want to support a later image version.

The "running Rancher in a Rancher stack" is the same chicken-and-egg issue we have with running the VMWare Virtual Centre in the VMWare cluster that it manages.  Yes, it can work, but you have to have a way to get it back up if everything is shut down -- and you can end up with  some gnary dependencies.

**Pull request closed without merging**
