### PR TITLE
Select LDAP attribute for  search  username

### PR DESCRIPTION
**Pull request by Rhoa**

### CODE REVIEW

**Comment by cloudnautique** [comment]
@sshipway thoughts?

@Rhoa, we will need to squash the commits down before merging.

**Comment by vincent99** [comment]
@cloudnautique There's a button in GitHub to squash and merge now, so the contributor doesn't really need to do it anymore.

**Comment by sshipway** [comment]
@Rhoa - This would need to be done for the newly merged 1/ template (req #99 ) as well as the original 0/ template.  Sorry for moving the goalposts.

If you are going to parameterise the username attribute, is using an enum the right way to go?  Maybe just make it a text field - so as to support other attributes than cn and uid... people may have custom schemas or use the mail attribute as the username

**Comment by cloudnautique** [comment]
@rhoa @sshipway what is the story with this PR? Should it be closed?

**Comment by sshipway** [comment]
I think the PR should be extended to include the same changes in the newer 1/ template before merging?  No point in making changes only to the older template.

**Comment by cloudnautique** [comment]
closing. Please open a new PR if you'd like to address issues.

**Pull request closed without merging**
