### PR TITLE
adding Nexus OSS template

### PR DESCRIPTION
**Pull request by kerryhatcher**

### CODE REVIEW

**Comment by cloudnautique** [comment]
This looks good, can you rebase with master so we can get a clean CI run on it?
Thanks!

**Comment by kerryhatcher** [comment]
@cloudnautique  looks like drone fails with: Error: missing Docker image. Is that a problem with my template?

**Comment by galal-hussein** [comment]
@kerryhatcher Can you please unmerge the latest commit, then rebase with master.

Also the SVG image doesn't seem to appear, can you check that, thanks.

**Comment by rawmind0** [comment]
Hi @kerryhatcher ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by rawmind0** [comment]
Closing due to inactivity. Please, reopen it, if you are still interested.

**Pull request closed without merging**
