### PR TITLE
Added New Prometheus Stack with Alertmanager and also added new Grafana Dashbaord which shows Rancher Status

### PR DESCRIPTION
**Pull request by abhijeetka**
within new graf-db image , users will have following features.
1. All Rancher Services
2. All Rancher Stack
3. All Active Rancher Services
4. All Active Rancher Stack
5. Name of all Rancher Services with its Status.

rancher new setup

### CODE REVIEW

**Comment by abhijeetka** [comment]
Any Updates on this?

**Comment by abhijeetka** [comment]
prometheus stack

This gives Email Alerts

image

**Comment by abhijeetka** [comment]
@Rucknar : Please have a look

**Comment by Rucknar** [comment]
Apologies @abhijeetka I hadn't spotted this until now! I'll run through it shortly!

**Comment by Rucknar** [comment]
Hey @abhijeetka, had a quick browse over the changes... few questions: 

* Does email have to be required? Most implementations i've seen use alertmanager to notify things like slack or upstream monitoring systems. If possible, we should make this an optional thing for those who want email alerting. 
* It's worth squashing your commits to keep the overall community-catalog nice and clean. 
* I try not use latest, for instance i'm likely to upgrade to grafana 3.0 soon, this would break using the latest tag for older versions.

**Comment by abhijeetka** [comment]
@Rucknar : Thanks for looking into it and sorry for delay in my reply.. i was busy with other stuff. So answering you question,

1.Email is not required, for now i have used some SMTP server which will send Emails, if user wants to get email , within template i have provided with a field for entering email address. if he doesnt add any address its fine.

2. i will work on squashing the commits. however i need your help, i wanted to add two maintainers however the build was failing, do you have any idea about this?

3. Sure i will update the catalog with specific tag, however on docker hub its latest, so if you change the tag i will change the updated tag within catalog.

For now i was planning to publish this Template.
also, i am planning for updating the template with Slack, webhook and for PagerDuty in coming time.

I have started working on Slack and Webhook, i will let you know once i am done for review and suggestions.

**Comment by abhijeetka** [comment]
@Rucknar i think this is good to go for now. Let me know if you have some more suggestions.

@vincent99: can you test and merge this pull request.

**Pull request closed without merging**
