### PR TITLE
update to stable release of grafana

### PR DESCRIPTION
**Pull request by xinity**

### CODE REVIEW

**Comment by cloudnautique** [comment]
This failed CI, I believe the config.yaml file will need to be updated to reflect the version change.

**Comment by xinity** [comment]
i'll try to fix it by next week

**Comment by cloudnautique** [comment]
If you rebase off of master this will get run correctly through CI.

**Comment by rawmind0** [comment]
Hi @xinity ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by rawmind0** [comment]
Rebased by newest PR

**Pull request closed without merging**
