### PR TITLE
update netdata catalog image

### PR DESCRIPTION
**Pull request by galal-hussein**

### CODE REVIEW

**Comment by elboletaire** [comment]
I'm sorry but I find this image terrible compared to the one I provided 😕

**Comment by elboletaire** [comment]
BTW, the image you provide IS NOT an official logo whilst the one I provided was created following the style of the application logo.

**Comment by elboletaire** [comment]
Ok, now I see that's the new favicon for netdata... it's terrible xD

**Comment by galal-hussein** [comment]
@elboletaire I just added the same image as the favicon :)

**Comment by elboletaire** [comment]
On top of my logo? Because does not seem my logo... I mean, I created that logo downloading the font they're using inside of netdata, but the new font seems a bit ugly compared to that one 😕

**Pull request merged**
