### PR TITLE
Update jenkins

### PR DESCRIPTION
**Pull request by ovidiub13**
This is a redone of #222.

### CODE REVIEW

**Comment by ovidiub13** [comment]
I've updated to the current latest: 2.19.4, which I'm currently using, but not from the catalog.

**Comment by rawmind0** [comment]
Hi @ovidiub13 ... 

I've tested the package and seems to work well doing a new installation and updating from previous one. 
LGTM

Thanks so much for your patience and your effort...

**Comment by ovidiub13** [comment]
Thank you for the approval, but I can't merge it. I don't have the permissions.

**Comment by rawmind0** [comment]
Don't worry...I merge it right now... :)

Thanks so much for the PR and the contribution....

**Pull request merged**
