### PR TITLE
Adding osTicket Stack

### PR DESCRIPTION
**Pull request by matisku**
## What is inside osTicket Stack?
- [osTicket Server](http://osticket.com/) + Sidekick with plugins storage
- MySQL Database + Sidekick with storage
## Info
- In default osTicket stack will create "osticket" MySQL database with osticket user.
- Once osTicket will start, make sure you setup correct information in setup page.
- For easy upgrades there are sidekicks for both osTicket and MySQL with dedicated storage.
- osTicket plugins are installed on sidekick in /data/upload/include/plugins
## First Run

Once osTicket Server starts:
- Go to http://[IP]:[PORT]/scp and login with default credentials:
- **username**: ostadmin
- **password**: Admin1

### CODE REVIEW

**Comment by matisku** [comment]
Any idea why tests failed?
My drone.ci is passing without any problem: https://drone.io/github.com/matisku/community-catalog/46
What I'm missing here?

**Comment by galal-hussein** [comment]
@matisku Thanks for the contribution, i can see that osticket server container is failing with the following message:

```
11/28/2016 9:12:03 PM Missing required environmental variable: MYSQL_PASSWORD
```

Can you also rebase with master to make sure the CI run is green.

**Comment by rawmind0** [comment]
Hi @matisku ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by matisku** [comment]
No problem. I'll close this pull request for now.

**Pull request closed without merging**
