### PR TITLE
add new version of gogs

### PR DESCRIPTION
**Pull request by mastertinner**
fix and update gogs

### CODE REVIEW

**Comment by cloudnautique** [comment]
Where does Gogs store all of its data? Does it store anything on disk? If so, it will be lost in the upgrade.

**Comment by rawmind0** [comment]
Hi @mastertinner ,

I apologize, but i rewrites history git repo by mistake. In order to be able to treat PR, it's needed that you fetch the rewritten history and rebase any local changes into the rewritten history.

I'm sorry, thank so much...

**Comment by ununseptium** [comment]
I would suggest to close this, i don't think that something will happen anymore to this.

**Comment by mastertinner** [comment]
Since I deleted the source branch, I'll go ahead and close this and create a new, up to date PR.

**Pull request closed without merging**
