### PR TITLE
Add ELK v5.4.1 stacks

### PR DESCRIPTION
**Pull request by dm**
Hi all,

I'd like to bring this full ELK stack (with latest v5.4.1) into the community catalog (actually two stacks; a simpler suitable for development, and a fully scalable version).

More details on my [own project repo](https://github.com/dm/rancher-catalog-elk).

I'm sure this might need some improvements, so feel free to give some feedback.

Cheers,
Dan

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @dm ... Thanks so much for the PR....

Is not the already existing version of es v5.4.2 useful for you??  https://github.com/rancher/community-catalog/pull/526

Otherwise, you don't need to different versions of the package in order to add loadbalancer or not. Just use a variable and docker-compose.yml.tpl just to deploy or not loadbalancer. Same for non scalable version. Could you unify it in just one version with different variables/options?? 

Thanks....

**Comment by dm** [comment]
Hi @rawmind0,

Note that this is different from an ElasticSearch-only cluster and if focused on the whole **ELK** stack (ElasticSearch, Logstash, Kibana), as well as a few extras for these: Logstash (Collector & Indexer), Logspout, Redis, Cerebro and Curator. So I wanted these to be plugged in.

The load balancer was really only need for testing and a specific deployment; and can be removed to bring this in line with remaining catalog items; I can care for this, as well as bring these up to the latest v5.4.3, as soon as I have a bit of time.

Cheers,
Dan

**Comment by rawmind0** [comment]
@dm got it the target of the package... 

could you please, unify the 3 different versions into one with the name elk-stack and using docker-compose.yml.tpl ??  As an example, please take a look at https://github.com/rancher/community-catalog/blob/master/templates/gocd/0/docker-compose.yml.tpl 

Best regards...

**Comment by cjellick** [comment]
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

**Comment by dm** [comment]
> @dm got it the target of the package...
> 
> could you please, unify the 3 different versions into one with the name elk-stack and using docker-compose.yml.tpl ?? As an example, please take a look at https://github.com/rancher/community-catalog/blob/master/templates/gocd/0/docker-compose.yml.tpl

@rawmind0 @cjellick totally missed the notification on the above, and only changed stuff that we needed.
I haven't touched this in ages, so thanks for closing.

If I need to pick up ELK again for Rancher I'll be sure to reopen and update according to the above suggestion.

Cheers
Dan

**Pull request closed without merging**
