### PR TITLE
Added Gitea

### PR DESCRIPTION
**Pull request by kolaente**
This PR adds Gitea to the Rancher Catalog.

Gitea is a lightweight Open-Source git client, forked from Gogs in 2016/11.

More: https://try.gitea.io

I couldn't find any info about contributing to the catalog, I hope I'm doing it right.

### CODE REVIEW

**Comment by DevKyleS** [comment]
My thoughts are to move to their latest branch, which points to v1.2.3.
https://github.com/go-gitea/gitea/releases/latest

**Comment by kolaente** [comment]
Yes, you're right, but 1.3 will be released soon... shoud I modify it to 1.2.3 or wait for 1.3?

**Comment by kolaente** [comment]
As Gitea recently released version 1.3, I updated the template.

**Comment by DevKyleS** [comment]
Looks fantastic to me, I haven't tested. Now if we can get someone to merge it (that's not me, I don't have rights).

**Comment by DevKyleS** [comment]
@chrisurwin Is this ready to be merged?

**Comment by kolaente** [comment]
Cool thanks!

**Pull request merged**
